#ifndef CONFIG_H
#define CONFIG_H

#define CHIP8_TOTAL_MEMORY 4096
#define CHIP8_START_RAM 0x000
#define CHIP8_LOAD_ADDRESS 0x200
#define CHIP8_STACK_SIZE 16

#define CHIP8_TOTAL_KEYS 16
#define NUM_GP_REGISTERS 16
#define CHIP_8_SCREEN_WIDTH 64
#define CHIP_8_SCREEN_HEIGHT 32
#define CHIP_8_UPSCALER 10

#endif 